import { ahmednagar, akola, amravati, aurangabad, beed, bhandara, buldhana, chandrapur, dhule, gadchiroli, gondia, hingoli, jalgaon, jalna, kolhapur, latur, mumbai, nagpur, nanded, nandurbar, nashik, osmanabad, parbhani, pune, ratnagiri, sangli, satara, sindhudurg, solapur, thane, wardha, washim, yavatmal } from "./talukas-data"
import { haveli, mulshi, shirur, khed, maval, baramati, daund, indapur, bhor, purandar, velhe, ambegaon, junnar, mumbaiCity, mumbaiSuburban, nagpurUrban, nagpurRural, hingna, kamptee, katol, kuhi, narkhed, parseoni, ramtek, saoner, umred, bhiwapur, kalameshwar, mauda, igatpuri, dindori, peint, trimbakeshwar, kalwan, deola, surgana, baglan, malegaon, nandgaon, chandwad, yeola, niphad, sinnar, gangapur, paithan, kannad, sillod, vaijapur, khuldabad, soegaon, phulambri, kalyan, ulhasnagar, ambernath, bhiwandi, murbad, shahapur, solapurNorth, solapurSouth, akkalkot, barshi, karmala, madha, malshiras, mangalvedhe, mohol, pandharpur, sangole, karvir, panhala, hatkanangle, shirol, radhanagari, gaganbawada, kagal, bhudargad, ajra, gadhinglaj, chandgad, shahuwadi, miraj, kavathemahankal, tasgaon, jath, khanapur, atpadi, shirala, walwa, palus, kadegaon, karad, patan, jaoli, koregaon, wai, khatav, phaltan, man, khandala, mahableshwar, sangameshwar, lanja, rajapur, chiplun, guhagar, dapoli, mandangad, kudal, sawantwadi, kankavli, vaibhavwadi, malwan, deogad, dodamarg, vengurla, jamner, erandol, dharangaon, bhusawal, raver, muktainagar, bodwad, yawal, amalner, parola, chopda, pachora, bhadgaon, chalisgaon, sakri, shirpur, sindkhede, navapur, shahada, talode, akkalkuwa, akrani , sangamner, kopargaon, shrirampur, nevasa, shevgaon, pathardi, jamkhed, karjat, srigonda, parner, akole, rahuri, rahata, ashti, patoda, shirurKasar, georai, majalgaon, wadwani, kaij, dharur, parli, ambajogai, tuljapur, omerga, lohara, kallamb, bhum, paranda, washi, bhokardan, jafrabad, badnapur, ambad, ghansawangi, partur, mantha, sonpeth, gangakhed, pathri, manwath, palam, selu, jintur, purna, sengaon, kalamnuri, basmath, aundhaNagnath, aradhapur, mudkhed, bhokar, hadgaon, kinwat, mahur, degloor, mukhed, kandhar, loha, naigaon, dharmabad, biloli, umri, himayatnagar, renapur, ahmedpur, jalkot, chakur, shirurAnantpal, ausa, nilanga, devani, udgir, akot, telhara, balapur, patur, murtizapur, barshitakli, achalpur, chandurbazar, morshi, warud, daryapur, anjangaonSurji, chandurRailway, dhamangaonRailway, tiosa, bhatkuli, nandgaonKhandeshwar, dharni, chikhalda, chikhli, deulgaonRaja, khamgaon, shegaon, malkapur, motala, nandura, jalgaonJamod, sangrampur, sindkhedRaja, mehkar, lonar, malegaonWashim, risod, mangrulpir, karanja, manora, arni, babulgaon, kalamb, darwha, digras, ner, pusad, umarkhed, mahargaon, kelapur, ralegaon, ghatanji, wani, maregaon, zariJamni, deoli, seloo, arvi, ashtiWardha, karanjaWardha, hinganghat, samudrapur, ballarpur, bhadravati, chimur, warora, nagbhid, brahmapuri, sindewahi, mul, saoli, gondpipri, rajura, korphana, jivati, pombhurna, dhanora, chamorshi, mulchera, desiganj, armori, kurkheda, korchi, bhamragad, etapalli, sirongaon, arayamond, tumsar, pauni, mohadi, sakoli, lakhani, lakhandur, tirora, goregaon, arjunimorgaon, deori, amgaon, salekasa, sadakArjuni, puneCity, nashikCity, aurangabadCity } from "./villages-data";

// Mock data for districts
export const districts = [  
  { id: "ahmednagar", name: "अहिल्यानगर", stateId: "maharashtra" },  
  { id: "aurangabad", name: "छ. संभाजीनगर", stateId: "maharashtra" },
  { id: "pune", name: "पुणे", stateId: "maharashtra" },
  { id: "mumbai", name: "मुंबई", stateId: "maharashtra" },
  { id: "nagpur", name: "नागपूर", stateId: "maharashtra" },
  { id: "nashik", name: "नाशिक", stateId: "maharashtra" },
  { id: "thane", name: "ठाणे", stateId: "maharashtra" },
  { id: "solapur", name: "सोलापूर", stateId: "maharashtra" },
  { id: "kolhapur", name: "कोल्हापूर", stateId: "maharashtra" },
  { id: "sangli", name: "सांगली", stateId: "maharashtra" },
  { id: "satara", name: "सातारा", stateId: "maharashtra" },
  { id: "ratnagiri", name: "रत्नागिरी", stateId: "maharashtra" },
  { id: "sindhudurg", name: "सिंधुदुर्ग", stateId: "maharashtra" },
  { id: "jalgaon", name: "जळगाव", stateId: "maharashtra" },
  { id: "dhule", name: "धुळे", stateId: "maharashtra" },
  { id: "nandurbar", name: "नंदुरबार", stateId: "maharashtra" },
  { id: "beed", name: "बीड", stateId: "maharashtra" },
  { id: "osmanabad", name: "उस्मानाबाद", stateId: "maharashtra" },
  { id: "jalna", name: "जालना", stateId: "maharashtra" },
  { id: "parbhani", name: "परभणी", stateId: "maharashtra" },
  { id: "hingoli", name: "हिंगोली", stateId: "maharashtra" },
  { id: "nanded", name: "नांदेड", stateId: "maharashtra" },
  { id: "latur", name: "लातूर", stateId: "maharashtra" },
  { id: "akola", name: "अकोला", stateId: "maharashtra" },
  { id: "amravati", name: "अमरावती", stateId: "maharashtra" },
  { id: "buldhana", name: "बुलढाणा", stateId: "maharashtra" },
  { id: "washim", name: "वाशीम", stateId: "maharashtra" },
  { id: "yavatmal", name: "यवतमाळ", stateId: "maharashtra" },
  { id: "wardha", name: "वर्धा", stateId: "maharashtra" },
  { id: "chandrapur", name: "चंद्रपूर", stateId: "maharashtra" },
  { id: "gadchiroli", name: "गडचिरोली", stateId: "maharashtra" },
  { id: "bhandara", name: "भंडारा", stateId: "maharashtra" },
  { id: "gondia", name: "गोंदिया", stateId: "maharashtra" },
]

// Mock data for villages
export const villages = [
  ...new Set([
  ...puneCity,
  ...haveli,
  ...mulshi,
  ...shirur,
  ...khed,
  ...maval,
  ...baramati,
  ...daund,
  ...indapur,
  ...bhor,
  ...purandar,
  ...velhe,
  ...ambegaon,
  ...junnar,
  ...mumbaiCity,
  ...mumbaiSuburban,
  ...nagpurUrban,
  ...nagpurRural,
  ...hingna,
  ...kamptee,
  ...katol,
  ...kuhi,
  ...narkhed,
  ...parseoni,
  ...ramtek,
  ...saoner,
  ...umred,
  ...bhiwapur,
  ...kalameshwar,
  ...mauda,
  ...nashikCity,
  ...igatpuri,
  ...dindori,
  ...peint,
  ...trimbakeshwar,
  ...kalwan,
  ...deola,
  ...surgana,
  ...baglan,
  ...malegaon,
  ...nandgaon,
  ...chandwad,
  ...yeola,
  ...niphad,
  ...sinnar,
  ...aurangabadCity,
  ...gangapur,
  ...paithan,
  ...kannad,
  ...sillod,
  ...vaijapur,
  ...khuldabad,
  ...soegaon,
  ...phulambri,
  ...kalyan,
  ...ulhasnagar,
  ...ambernath,
  ...bhiwandi,
  ...murbad,
  ...shahapur,
  ...solapurNorth,
  ...solapurSouth,
  ...akkalkot,
  ...barshi,
  ...karmala,
  ...madha,
  ...malshiras,
  ...mangalvedhe,
  ...mohol,
  ...pandharpur,
  ...sangole,
  ...karvir,
  ...panhala,
  ...hatkanangle,
  ...shirol,
  ...radhanagari,
  ...gaganbawada,
  ...kagal,
  ...bhudargad,
  ...ajra,
  ...gadhinglaj,
  ...chandgad,
  ...shahuwadi,
  ...miraj,
  ...kavathemahankal,
  ...tasgaon,
  ...jath,
  ...khanapur,
  ...atpadi,
  ...shirala,
  ...walwa,
  ...palus,
  ...kadegaon,
  ...karad,
  ...patan,
  ...jaoli,
  ...koregaon,
  ...wai,
  ...khatav,
  ...phaltan,
  ...man,
  ...khandala,
  ...mahableshwar,
  ...sangameshwar,
  ...lanja,
  ...rajapur,
  ...chiplun,
  ...guhagar,
  ...dapoli,
  ...mandangad,
  ...kudal,
  ...sawantwadi,
  ...kankavli,
  ...vaibhavwadi,
  ...malwan,
  ...deogad,
  ...dodamarg,
  ...vengurla,
  ...jamner,
  ...erandol,
  ...dharangaon,
  ...bhusawal,
  ...raver,
  ...muktainagar,
  ...bodwad,
  ...yawal,
  ...amalner,
  ...parola,
  ...chopda,
  ...pachora,
  ...bhadgaon,
  ...chalisgaon,
  ...sakri,
  ...shirpur,
  ...sindkhede,
  ...navapur,
  ...shahada,
  ...talode,
  ...akkalkuwa,
  ...akrani ,
  ...sangamner,
  ...kopargaon,
  ...shrirampur,
  ...nevasa,
  ...shevgaon,
  ...pathardi,
  ...jamkhed,
  ...karjat,
  ...srigonda,
  ...parner,
  ...akole,
  ...rahuri,
  ...rahata,
  ...ashti,
  ...patoda,
  ...shirurKasar,
  ...georai,
  ...majalgaon,
  ...wadwani,
  ...kaij,
  ...dharur,
  ...parli,
  ...ambajogai,
  ...tuljapur,
  ...omerga,
  ...lohara,
  ...kallamb,
  ...bhum,
  ...paranda,
  ...washi,
  ...bhokardan,
  ...jafrabad,
  ...badnapur,
  ...ambad,
  ...ghansawangi,
  ...partur,
  ...mantha,
  ...sonpeth,
  ...gangakhed,
  ...pathri,
  ...manwath,
  ...palam,
  ...selu,
  ...jintur,
  ...purna,
  ...sengaon,
  ...kalamnuri,
  ...basmath,
  ...aundhaNagnath,
  ...aradhapur,
  ...mudkhed,
  ...bhokar,
  ...hadgaon,
  ...kinwat,
  ...mahur,
  ...degloor,
  ...mukhed,
  ...kandhar,
  ...loha,
  ...naigaon,
  ...dharmabad,
  ...biloli,
  ...umri,
  ...himayatnagar,
  ...renapur,
  ...ahmedpur,
  ...jalkot,
  ...chakur,
  ...shirurAnantpal,
  ...ausa,
  ...nilanga,
  ...devani,
  ...udgir,
  ...akot,
  ...telhara,
  ...balapur,
  ...patur,
  ...murtizapur,
  ...barshitakli,
  ...achalpur,
  ...chandurbazar,
  ...morshi,
  ...warud,
  ...daryapur,
  ...anjangaonSurji,
  ...chandurRailway,
  ...dhamangaonRailway,
  ...tiosa,
  ...bhatkuli,
  ...nandgaonKhandeshwar,
  ...dharni,
  ...chikhalda,
  ...chikhli,
  ...deulgaonRaja,
  ...khamgaon,
  ...shegaon,
  ...malkapur,
  ...motala,
  ...nandura,
  ...jalgaonJamod,
  ...sangrampur,
  ...sindkhedRaja,
  ...mehkar,
  ...lonar,
  ...malegaonWashim,
  ...risod,
  ...mangrulpir,
  ...karanja,
  ...manora,
  ...arni,
  ...babulgaon,
  ...kalamb,
  ...darwha,
  ...digras,
  ...ner,
  ...pusad,
  ...umarkhed,
  ...mahargaon,
  ...kelapur,
  ...ralegaon,
  ...ghatanji,
  ...wani,
  ...maregaon,
  ...zariJamni,
  ...deoli,
  ...seloo,
  ...arvi,
  ...ashtiWardha,
  ...karanjaWardha,
  ...hinganghat,
  ...samudrapur,
  ...ballarpur,
  ...bhadravati,
  ...chimur,
  ...warora,
  ...nagbhid,
  ...brahmapuri,
  ...sindewahi,
  ...mul,
  ...saoli,
  ...gondpipri,
  ...rajura,
  ...korphana,
  ...jivati,
  ...pombhurna,
  ...dhanora,
  ...chamorshi,
  ...mulchera,
  ...desiganj,
  ...armori,
  ...kurkheda,
  ...korchi,
  ...bhamragad,
  ...etapalli,
  ...sirongaon,
  ...arayamond,
  ...tumsar,
  ...pauni,
  ...mohadi,
  ...sakoli,
  ...lakhani,
  ...lakhandur,
  ...tirora,
  ...goregaon,
  ...arjunimorgaon,
  ...deori,
  ...amgaon,
  ...salekasa,
  ...sadakArjuni
  ])
];

export function getTalukasByDistrict(districtId) {
  return talukas.filter((taluka) => taluka.districtId === districtId)
}

export function getVillagesByTaluka(talukaId) {
  return villages.filter((village) => village.talukaId === talukaId)
}

export function getDistrictById(id) {
  return districts.find((district) => district.id === id)
}

export function getTalukaById(id) {
  return talukas.find((taluka) => taluka.id === id)
}

export function getVillageById(id) {
  return villages.find((village) => village.id === id)
}

