const marketTypesDetails = {
	DistrictCommodityGird : {
		name : "जिल्हा शेतमाल निहाय/DistrictCommodityGird",
		tableId : "DistrictCommodityGird",
		SelectOptionId : "drpDistrictCommodity",
		tableName : "DistrictCommodityGird",
		subTabID : "DistrictCommodityWiseGirdID",
		seoMeta : {
			seo_title: "jilhanihay Bhajar Bhav",
			seo_description: "jilhanihay Bhajar bhav",
			keywords: "jilhanihay, bajar, bhav",
			og_url : "some url",
			canonical_url: "some url",
			featured_image: "company logo path",
			author: "Jio Kheti",
			published_date: "12/12/2012", 
			updated_date: "12/12/2012"
		},
		DropdownOptions : [
			{ 
				name: "अकोला",
				code: "32", 
				slug: "akola-bhajarbhav",
				seoMeta : {
					seo_title: "Akola Bhajar Bhav",
					seo_description: "Akola Bhajar bhav",
					keywords: "akila, bajar, bhav",
					og_url : "some url",
					canonical_url: "some url",
					featured_image: "company logo path",
					author: "Jio Kheti",
					published_date: "12/12/2012", 
					updated_date: "12/12/2012"
				}
			},
			{ name: "अमरावती", code: "33", slug: "amravati-bhajarbhav" },
			{ name: "अहिल्यानगर", code: "16", slug: "ahilyanagar-bhajarbhav" },
			{ name: "कोल्हापूर", code: "20", slug: "kolhapur-bhajarbhav" },
			{ name: "गडचिरोली", code: "38", slug: "gadchiroli-bhajarbhav" },
			{ name: "गोंदिया", code: "44", slug: "gondia-bhajarbhav" },
			{ name: "चंद्रपुर", code: "37", slug: "chandrapur-bhajarbhav" },
			{ name: "छत्रपती संभाजीनगर", code: "25", slug: "sambhaji-nagar-bhajarbhav" },
			{ name: "जळगाव", code: "18", slug: "jalgoan-bhajarbhav" },
			{ name: "जालना", code: "27", slug: "jalana-bhajarbhav" },
			{ name: "ठाणे", code: "14", slug: "thane-bhajarbhav" },
			{ name: "धाराशिव", code: "30", slug: "dharashiv-bhajarbhav" },
			{ name: "धुळे", code: "17", slug: "dhule-bhajarbhav" },
			{ name: "नंदुरबार", code: "41", slug: "nadurbar-bhajarbhav" },
			{ name: "नांदेड", code: "29", slug: "nanded-bhajarbhav"},
			{ name: "नागपूर", code: "39", slug: "nagpur-bhajarbhav" },
			{ name: "नाशिक", code: "19", slug: "nashik-bhajarbhav" },
			{ name: "परभणी", code: "31", slug: "parabhani-bhajarbhav" },
			{ name: "पालघर", code: "45", slug: "palghar-bhajarbhav" },
			{ name: "पुणे", code: "21", slug: "pune-bhajarbhav" },
			{ name: "बीड", code: "26", slug: "beed-bhajarbhav" },
			{ name: "बुलढाणा", code: "34", slug: "buladhana-bhajarbhav" },
			{ name: "भंडारा", code: "36", slug: "bhandara-bhajarbhav" },
			{ name: "मंबई", code: "11", slug: "mumbai-bhajarbhav" },
			{ name: "यवतमाळ", code: "35", slug: "yavatmaal-bhajarbhav" },
			{ name: "रत्नागिरी", code: "13", slug: "ratnagiri-bhajarbhav" },
			{ name: "रायगड", code: "12", slug: "raigad-bhajarbhav" },
			{ name: "लातूर", code: "28", slug: "latur-bhajarbhav" },
			{ name: "वर्धा", code: "40", slug: "vardha-bhajarbhav" },
			{ name: "वाशिम", code: "42", slug: "vashim-bhajarbhav" },
			{ name: "सांगली", code: "22", slug: "sangali-bhajarbhav" },
			{ name: "सातारा", code: "23", slug: "satara-bhajarbhav" },
			{ name: "सोलापूर", code: "24", slug: "solapur-bhajarbhav" },
			{ name: "हिंगोली", code: "43", slug: "hingoli-bhajarbhav" }
		  ]
		  
	},
	CommodityGird : {
		name : "शेतमाल निहाय/CommodityGird",
		tableId : "CommodityGird",
		SelectOptionId : "drpCommodities",
		tableName : "CommodityGird",
		subTabID : "CommodityGirdID",
		meta : {
			seo_title: "Akola Bhajar Bhav",
			seo_description: "Akola Bhajar bhav",
			keywords: "akila, bajar, bhav",
			og_url : "some url",
			canonical_url: "some url",
			featured_image: "company logo path",
			author: "Jio Kheti",
			published_date: "12/12/2012", 
			updated_date: "12/12/2012"
		},
		DropdownOptions : [
			{ 
				name: "अंजीर", 
				code: "07003", 
				slug: "anjir-bhajarbhav",
				seoMeta : {
					seo_title: "अंजीर Bhajar Bhav",
					seo_description: "अंजीर Bhajar bhav",
					keywords: "अंजीर, bajar, bhav",
					og_url : "some url",
					canonical_url: "some url",
					featured_image: "company logo path",
					author: "Jio Kheti",
					published_date: "12/12/2012", 
					updated_date: "12/12/2012"
				}
			},
			{ name: "अंजीर (सुके)", code: "10027", slug: "anjir-suke-bhajarbhav" },
			{ name: "अंबाडी भाजी", code: "08003" },
			{ name: "अननस", code: "07002" },
			{ name: "अर्वी", code: "08005" },
			{ name: "अवाकाडो", code: "18008" },
			{ name: "आंबट चुका", code: "08004" },
			{ name: "आंबा", code: "07001" },
			{ name: "आईसबर्ग", code: "18003" },
			{ name: "आले", code: "08002" },
			{ name: "आले (सुंठ)", code: "10001" },
			{ name: "आवळा", code: "07042" },
			{ name: "आवळा", code: "08006" },
			{ name: "उडीद", code: "03022" },
			{ name: "उडीद डाळ", code: "03023" },
			{ name: "एरंडी", code: "04005" },
			{ name: "ओवा", code: "04014" },
			{ name: "कंद", code: "08034" },
			{ name: "कडबा", code: "11003" },
			{ name: "कढिपत्ता", code: "08031" },
			{ name: "करडई", code: "04008" },
			{ name: "करडई (भाजी)", code: "08038" },
			{ name: "कलिंगड", code: "07011" },
			{ name: "कांदा", code: "08035" },
			{ name: "कांदा पात", code: "08036" },
			{ name: "काकडी", code: "08033" },
			{ name: "काजू", code: "10010" },
			{ name: "कापूस", code: "01001" },
			{ name: "कारली", code: "08039" },
			{ name: "कालवड", code: "09020" },
			{ name: "कुलथी", code: "03010" },
			{ name: "केळी", code: "07014" },
			{ name: "केळी (कच्ची)", code: "08040" },
			{ name: "कैरी", code: "08032" },
			{ name: "कोंबडी", code: "09009" },
			{ name: "कोथिंबिर", code: "08044" },
			{ name: "कोबी", code: "08041" },
			{ name: "कोहळा", code: "08043" },
			{ name: "खरबुज", code: "07044" },
			{ name: "गवार", code: "08024" },
			{ name: "गहू", code: "02009" },
			{ name: "गाजर", code: "08022" },
			{ name: "गाय", code: "09005" },
			{ name: "गुलाब", code: "16003" },
			{ name: "गुळ", code: "06001" },
			{ name: "घेवडा", code: "08025" },
			{ name: "घेवडा बी", code: "03005" },
			{ name: "घोडा", code: "09006" },
			{ name: "घोसाळी (भाजी)", code: "08026" }
		] 
	}
}

module.exports = marketTypesDetails;